# Generated by Django 4.2.1 on 2023-06-02 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_api', '0003_alter_project_options_contributor_permission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='permission',
            field=models.IntegerField(choices=[(1, 'Contributeur ou Contributrice'), (9, 'Auteur ou Autrice')], default=1),
        ),
    ]
